package com.igorzaitcev.agent.status;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-16T15:38:15.993+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "CreateStatusServiceService",
                  wsdlLocation = "file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/StatusCreate.wsdl",
                  targetNamespace = "http://service.igorzaitcev.com/")
public class CreateStatusServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.igorzaitcev.com/", "CreateStatusServiceService");
    public final static QName CreateStatusServicePort = new QName("http://service.igorzaitcev.com/", "CreateStatusServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/StatusCreate.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateStatusServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/StatusCreate.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateStatusServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateStatusServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateStatusServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateStatusServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateStatusServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateStatusServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StatusServerPortType
     */
    @WebEndpoint(name = "CreateStatusServicePort")
    public StatusServerPortType getCreateStatusServicePort() {
        return super.getPort(CreateStatusServicePort, StatusServerPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatusServerPortType
     */
    @WebEndpoint(name = "CreateStatusServicePort")
    public StatusServerPortType getCreateStatusServicePort(WebServiceFeature... features) {
        return super.getPort(CreateStatusServicePort, StatusServerPortType.class, features);
    }

}
