package com.igorzaitcev.soap.createcontract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-16T13:03:36.045+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ContractsServer",
                  wsdlLocation = "file:/Users/igorzaitcev/SpringToolSuite/bankapi/src/main/resources/wsdl/CreateContractsServer.wsdl",
                  targetNamespace = "http://createcontract.server.igorzaitcev.com")
public class ContractsServer extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://createcontract.server.igorzaitcev.com", "ContractsServer");
    public final static QName ContractsServerPort = new QName("http://createcontract.server.igorzaitcev.com", "ContractsServerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/igorzaitcev/SpringToolSuite/bankapi/src/main/resources/wsdl/CreateContractsServer.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContractsServer.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/igorzaitcev/SpringToolSuite/bankapi/src/main/resources/wsdl/CreateContractsServer.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContractsServer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContractsServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContractsServer() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ContractsServer(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContractsServer(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContractsServer(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ContractsServerPortType
     */
    @WebEndpoint(name = "ContractsServerPort")
    public ContractsServerPortType getContractsServerPort() {
        return super.getPort(ContractsServerPort, ContractsServerPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContractsServerPortType
     */
    @WebEndpoint(name = "ContractsServerPort")
    public ContractsServerPortType getContractsServerPort(WebServiceFeature... features) {
        return super.getPort(ContractsServerPort, ContractsServerPortType.class, features);
    }

}
