package com.igorzaitcev.soap.createcontract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-16T13:03:36.037+02:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://createcontract.server.igorzaitcev.com", name = "ContractsServerPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContractsServerPortType {

    @WebMethod(action = "http://igorzaitcev.com/NewOperation")
    @WebResult(name = "createContractsResponse", targetNamespace = "http://createcontract.server.igorzaitcev.com", partName = "parameters")
    public CreateContractsResponse createContracts(

        @WebParam(partName = "parameters", name = "createContractsRequest", targetNamespace = "http://createcontract.server.igorzaitcev.com")
        CreateContractsRequest parameters
    );
}
