package com.igorzaitcev.agent.contract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-16T15:36:45.940+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "CreateContractsServiceService",
                  wsdlLocation = "file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/ContractsCreate.wsdl",
                  targetNamespace = "http://service.igorzaitcev.com/")
public class CreateContractsServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.igorzaitcev.com/", "CreateContractsServiceService");
    public final static QName CreateContractsServicePort = new QName("http://service.igorzaitcev.com/", "CreateContractsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/ContractsCreate.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateContractsServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/ContractsCreate.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateContractsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateContractsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateContractsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateContractsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateContractsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateContractsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ContractsServerPortType
     */
    @WebEndpoint(name = "CreateContractsServicePort")
    public ContractsServerPortType getCreateContractsServicePort() {
        return super.getPort(CreateContractsServicePort, ContractsServerPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContractsServerPortType
     */
    @WebEndpoint(name = "CreateContractsServicePort")
    public ContractsServerPortType getCreateContractsServicePort(WebServiceFeature... features) {
        return super.getPort(CreateContractsServicePort, ContractsServerPortType.class, features);
    }

}
