package com.igorzaitcev.agent.client;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-16T15:34:00.978+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "CreateClientsServiceService",
                  wsdlLocation = "file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/ClientsCreate.wsdl",
                  targetNamespace = "http://service.igorzaitcev.com/")
public class CreateClientsServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.igorzaitcev.com/", "CreateClientsServiceService");
    public final static QName CreateClientsServicePort = new QName("http://service.igorzaitcev.com/", "CreateClientsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/ClientsCreate.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateClientsServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/igorzaitcev/SpringToolSuite/contarctsmanagment/src/main/resources/wsdl/ClientsCreate.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateClientsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateClientsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateClientsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateClientsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateClientsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateClientsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClientsServerPortType
     */
    @WebEndpoint(name = "CreateClientsServicePort")
    public ClientsServerPortType getCreateClientsServicePort() {
        return super.getPort(CreateClientsServicePort, ClientsServerPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientsServerPortType
     */
    @WebEndpoint(name = "CreateClientsServicePort")
    public ClientsServerPortType getCreateClientsServicePort(WebServiceFeature... features) {
        return super.getPort(CreateClientsServicePort, ClientsServerPortType.class, features);
    }

}
